### Recupera todas las películas
GET http://localhost:1234/movies

### Recuperar película por id
GET http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### Recuperar todas las películas por un género
GET http://localhost:1234/movies?genre=Action

### Crear una película con POST
POST http://localhost:1234/movies
Content-Type: application/json

{
  "sql": "SELECT * FROM users",
  "title": "The Godfather",
  "year": 1976,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Drama"
  ]
}

### Borrar una pelicula
DELETE http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3


### Actualizar una película con PATCH
PATCH http://localhost:1234/movies/56b37e51-494f-464b-8f35-d5c44d2c70f5
Content-Type: application/json

{
  "title": "Cambio de nombre",
  "year": 1901
}